#!/bin/sh

param="counters.ALL"

chips=`owdir | grep "\/1D\."`

if ! [ $? -eq 0 ]; then
	exit 1
fi 
	
for chip in $chips
	do echo "`date` ; read ; $chip ; $param ; `owread $chip/$param` ; ($?)"
done


