#!/bin/sh

stamp=`date`
param="type"

chips=`owdir | grep -E "\/[0-9A-Z]{2}\."`

if ! [ $? -eq 0 ]; then
	exit 1
fi

for chip in $chips
do
	echo "$stamp ; read ; $chip ; $param ; `owread $chip/$param` ; ($?)"
done

