#!/bin/bash
# Script for the exec plugin (collectd-exec(5))
#



the_pipe="/tmp/1w_sys_pipe"
trap "rm -f $the_pipe; exit" INT TERM EXIT

while true; do
  if [[ -p $the_pipe ]]; then
    if read -r line < $the_pipe; then
      echo "$line"
      sleep 0.3
    fi
  else
    mkfifo $the_pipe
  fi
  sleep 0.3
done
